spring:
  cloudinary:
    cloud_name: dh0qn5xbk
    api_key: 367863941559932
    api_secret: QVOQihDhOZc7KfdzVm2aPgC4nYs
  datasource:
    url: jdbc:mysql://localhost:3306/portfolio
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
